# Generated by Django 5.1.5 on 2025-04-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='poke_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
