# Generated by Django 5.1.5 on 2025-04-26 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='is_listed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
