# Generated by Django 5.1.5 on 2025-04-27 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_pokemon_is_listed_pokemon_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('denied', 'Denied')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_trade_offers', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_offers', to='collection.pokemon')),
                ('offered_pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_in_trade', to='collection.pokemon')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_trade_offers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
